import SwiftUI

// Generated by Supernova - do not modify manually
public struct AppMeasures {

    // Dimension
    public static let dimensionToken1 = 10 
    public static let dimensionToken2 = 10 

    // Border radius

    /// No radius
    public static let dimensionBorderRadiusNone = 0 
    public static let dimensionBorderRadiusSmall = 3 
    public static let dimensionBorderRadiusDefault = 5 
    public static let dimensionBorderRadiusMedium = 8 
    public static let dimensionBorderRadiusLarge = 12 

    /// Essentially a circle
    public static let dimensionBorderRadiusFull = 999 

    // Spacing
    public static let dimensionSpacing0 = 0 
    public static let dimensionSpacing2 = 2 
    public static let dimensionSpacing4 = 4 
    public static let dimensionSpacing8 = 8 
    public static let dimensionSpacing12 = 12 
    public static let dimensionSpacing16 = 16 
    public static let dimensionSpacing20 = 20 
    public static let dimensionSpacing24 = 24 
    public static let dimensionSpacing28 = 28 
    public static let dimensionSpacing32 = 32 
    public static let dimensionSpacing36 = 36 
    public static let dimensionSpacing40 = 40 

    // Opacity
    public static let dimensionOpacityDisabled = 50 

    // Border Radius
    public static let borderRadiusRadiusToken = 6 
    public static let borderRadiusRd = 10 
    public static let borderRadiusKelioMeasure = 3 
    public static let borderRadiusToken1 = 6 
    public static let borderRadiusSnRadius = 5 
}