import SwiftUI

// Generated by Supernova - do not modify manually
public extension View {

    func borderAbbott() -> some View {
        return self.border(Color(.sRGB, red: 193/255, green: 100/255, blue: 100/255, opacity: 1), width: 5) 
    }

    func borderEy4() -> some View {
        return self.border(Color(.sRGB, red: 218/255, green: 100/255, blue: 100/255, opacity: 1), width: 6) 
    }

    func borderBellBoarder() -> some View {
        return self.border(Color(.sRGB, red: 195/255, green: 102/255, blue: 102/255, opacity: 1), width: 4) 
    }

    func borderLaPosteBoarder() -> some View {
        return self.border(Color(.sRGB, red: 190/255, green: 128/255, blue: 128/255, opacity: 1), width: 3) 
    }

    func borderFossBoarder() -> some View {
        return self.border(Color(.sRGB, red: 212/255, green: 33/255, blue: 33/255, opacity: 1), width: 5) 
    }

    func borderBoarder() -> some View {
        return self.border(Color(.sRGB, red: 40/255, green: 27/255, blue: 27/255, opacity: 1), width: 5) 
    }

    func borderNewTestBoarderValue() -> some View {
        return self.border(Color(.sRGB, red: 205/255, green: 39/255, blue: 39/255, opacity: 1), width: 3) 
    }

    func borderKelkioBoarder() -> some View {
        return self.border(Color(.sRGB, red: 161/255, green: 247/255, blue: 44/255, opacity: 1), width: 3) 
    }

    func borderNewBoarder() -> some View {
        return self.border(Color(.sRGB, red: 226/255, green: 36/255, blue: 36/255, opacity: 1), width: 4) 
    }

    func borderName() -> some View {
        return self.border(Color(.sRGB, red: 219/255, green: 94/255, blue: 94/255, opacity: 1), width: 4) 
    }

    func borderBoarderSn() -> some View {
        return self.border(Color(.sRGB, red: 151/255, green: 52/255, blue: 52/255, opacity: 1), width: 3) 
    }

    func borderNewOne() -> some View {
        return self.border(Color(.sRGB, red: 187/255, green: 66/255, blue: 66/255, opacity: 1), width: 3) 
    }

    func borderToken1() -> some View {
        return self.border(Color(.sRGB, red: 125/255, green: 45/255, blue: 45/255, opacity: 1), width: 4) 
    }

    func borderToken2() -> some View {
        return self.border(Color(.sRGB, red: 172/255, green: 17/255, blue: 17/255, opacity: 1), width: 5) 
    }

    func borderToken3() -> some View {
        return self.border(Color(.sRGB, red: 235/255, green: 92/255, blue: 92/255, opacity: 1), width: 3) 
    }

    func borderSnBoarder() -> some View {
        return self.border(Color(.sRGB, red: 151/255, green: 35/255, blue: 35/255, opacity: 1), width: 3) 
    }

    func borderFsecure() -> some View {
        return self.border(Color(.sRGB, red: 189/255, green: 50/255, blue: 50/255, opacity: 1), width: 3) 
    }

    func borderToken4() -> some View {
        return self.border(Color(.sRGB, red: 0/255, green: 0/255, blue: 0/255, opacity: 1), width: 5) 
    }

    func borderSnBoarder() -> some View {
        return self.border(Color(.sRGB, red: 201/255, green: 106/255, blue: 106/255, opacity: 1), width: 3) 
    }

    func borderToken5() -> some View {
        return self.border(Color(.sRGB, red: 185/255, green: 42/255, blue: 42/255, opacity: 1), width: 6) 
    }

    func borderToken6() -> some View {
        return self.border(Color(.sRGB, red: 180/255, green: 59/255, blue: 59/255, opacity: 1), width: 4) 
    }

    func borderToken7() -> some View {
        return self.border(Color(.sRGB, red: 120/255, green: 20/255, blue: 20/255, opacity: 1), width: 4) 
    }

    func borderToken8() -> some View {
        return self.border(Color(.sRGB, red: 169/255, green: 68/255, blue: 68/255, opacity: 1), width: 4) 
    }

    func borderToken9() -> some View {
        return self.border(Color(.sRGB, red: 164/255, green: 61/255, blue: 61/255, opacity: 1), width: 5) 
    }

    func borderToken10() -> some View {
        return self.border(Color(.sRGB, red: 212/255, green: 33/255, blue: 33/255, opacity: 1), width: 3) 
    }

    func borderSnBoarder() -> some View {
        return self.border(Color(.sRGB, red: 146/255, green: 23/255, blue: 23/255, opacity: 1), width: 4) 
    }

    func borderSnBoarder() -> some View {
        return self.border(Color(.sRGB, red: 116/255, green: 33/255, blue: 33/255, opacity: 1), width: 5) 
    }

    func borderSnBoarder() -> some View {
        return self.border(Color(.sRGB, red: 192/255, green: 83/255, blue: 83/255, opacity: 1), width: 4) 
    }

    func borderSnBoarder() -> some View {
        return self.border(Color(.sRGB, red: 160/255, green: 54/255, blue: 54/255, opacity: 1), width: 3) 
    }

    func borderSnToken() -> some View {
        return self.border(Color(.sRGB, red: 143/255, green: 27/255, blue: 27/255, opacity: 1), width: 3) 
    }

    func borderName() -> some View {
        return self.border(Color(.sRGB, red: 192/255, green: 50/255, blue: 50/255, opacity: 1), width: 4) 
    }

    func borderToken11() -> some View {
        return self.border(Color(.sRGB, red: 149/255, green: 62/255, blue: 62/255, opacity: 1), width: 3) 
    }

    func borderToken12() -> some View {
        return self.border(Color(.sRGB, red: 194/255, green: 97/255, blue: 97/255, opacity: 1), width: 3) 
    }

    func borderToken13() -> some View {
        return self.border(Color(.sRGB, red: 0/255, green: 0/255, blue: 0/255, opacity: 1), width: 1) 
    }

    func borderToken14() -> some View {
        return self.border(Color(.sRGB, red: 193/255, green: 100/255, blue: 100/255, opacity: 1), width: 4) 
    }

    func borderToken15() -> some View {
        return self.border(Color(.sRGB, red: 88/255, green: 17/255, blue: 17/255, opacity: 1), width: 3) 
    }

    func borderBoarder() -> some View {
        return self.border(Color(.sRGB, red: 148/255, green: 41/255, blue: 41/255, opacity: 1), width: 4) 
    }

    func borderToken16() -> some View {
        return self.border(Color(.sRGB, red: 201/255, green: 79/255, blue: 79/255, opacity: 1), width: 4) 
    }

    func borderToken17() -> some View {
        return self.border(Color(.sRGB, red: 200/255, green: 87/255, blue: 87/255, opacity: 1), width: 3) 
    }

    func borderToken18() -> some View {
        return self.border(Color(.sRGB, red: 205/255, green: 102/255, blue: 102/255, opacity: 1), width: 3) 
    }

    func borderToken19() -> some View {
        return self.border(Color(.sRGB, red: 156/255, green: 77/255, blue: 77/255, opacity: 1), width: 4) 
    }

    func borderToken20() -> some View {
        return self.border(Color(.sRGB, red: 142/255, green: 36/255, blue: 36/255, opacity: 1), width: 3) 
    }

    func borderToken21() -> some View {
        return self.border(Color(.sRGB, red: 28/255, green: 24/255, blue: 24/255, opacity: 1), width: 4) 
    }

    func borderToken22() -> some View {
        return self.border(Color(.sRGB, red: 144/255, green: 24/255, blue: 24/255, opacity: 1), width: 5) 
    }

    func borderSnToken() -> some View {
        return self.border(Color(.sRGB, red: 47/255, green: 38/255, blue: 38/255, opacity: 1), width: 4) 
    }

    func borderSn() -> some View {
        return self.border(Color(.sRGB, red: 160/255, green: 44/255, blue: 44/255, opacity: 1), width: 3) 
    }

    func borderToken23() -> some View {
        return self.border(Color(.sRGB, red: 144/255, green: 29/255, blue: 29/255, opacity: 1), width: 3) 
    }

    func borderToken24() -> some View {
        return self.border(Color(.sRGB, red: 182/255, green: 70/255, blue: 70/255, opacity: 1), width: 3) 
    }

    func borderNewToken() -> some View {
        return self.border(Color(.sRGB, red: 201/255, green: 82/255, blue: 82/255, opacity: 1), width: 4) 
    }

    func borderSnBorader() -> some View {
        return self.border(Color(.sRGB, red: 180/255, green: 32/255, blue: 32/255, opacity: 1), width: 4) 
    }

    func borderToken25() -> some View {
        return self.border(Color(.sRGB, red: 186/255, green: 57/255, blue: 57/255, opacity: 1), width: 1) 
    }

    func borderBoarder() -> some View {
        return self.border(Color(.sRGB, red: 107/255, green: 23/255, blue: 23/255, opacity: 1), width: 3) 
    }

    func borderToken26() -> some View {
        return self.border(Color(.sRGB, red: 183/255, green: 72/255, blue: 72/255, opacity: 1), width: 3) 
    }

    func borderBoarder() -> some View {
        return self.border(Color(.sRGB, red: 154/255, green: 61/255, blue: 61/255, opacity: 1), width: 3) 
    }

    func borderToken27() -> some View {
        return self.border(Color(.sRGB, red: 0/255, green: 0/255, blue: 0/255, opacity: 1), width: 3) 
    }

    func borderSnToken() -> some View {
        return self.border(Color(.sRGB, red: 217/255, green: 74/255, blue: 74/255, opacity: 1), width: 4) 
    }

    func borderBorader() -> some View {
        return self.border(Color(.sRGB, red: 181/255, green: 76/255, blue: 76/255, opacity: 1), width: 4) 
    }

    func borderToken28() -> some View {
        return self.border(Color(.sRGB, red: 0/255, green: 0/255, blue: 0/255, opacity: 1), width: 1) 
    }

    func borderBoarder() -> some View {
        return self.border(Color(.sRGB, red: 103/255, green: 29/255, blue: 29/255, opacity: 1), width: 4) 
    }

    func borderToken29() -> some View {
        return self.border(Color(.sRGB, red: 114/255, green: 28/255, blue: 28/255, opacity: 1), width: 5) 
    }
}