import SwiftUI

// Generated by Supernova - do not modify manually
extension View {

    func borderBoarder() -> some View {
        return self.border(Color(.sRGB, red: 42/255, green: 100/255, blue: 97/255, opacity: 1), width: 2) 
    }

    func borderBoardeer2() -> some View {
        return self.border(Color(.sRGB, red: 202/255, green: 129/255, blue: 129/255, opacity: 1), width: 1) 
    }

    func borderRadius() -> some View {
        return self.border(Color(.sRGB, red: 0/255, green: 0/255, blue: 0/255, opacity: 1), width: 1) 
    }

    func border4Token() -> some View {
        return self.border(Color(.sRGB, red: 0/255, green: 0/255, blue: 0/255, opacity: 1), width: 1) 
    }

    func borderEmplifi() -> some View {
        return self.border(Color(.sRGB, red: 0/255, green: 0/255, blue: 0/255, opacity: 1), width: 1) 
    }

    func borderMistetemo() -> some View {
        return self.border(Color(.sRGB, red: 0/255, green: 0/255, blue: 0/255, opacity: 1), width: 1) 
    }
}