import SwiftUI

// Generated by Supernova - do not modify manually
public extension Text {

    func textStyleToken1() -> some View {
        return self
            .font(Font.custom("Abel-regular", size: 14))
            .textCase(.uppercase) 
    }

    func textStyleToken2() -> some View {
        return self
            .font(Font.custom("Inter-regular", size: 14))
    }

    func textStyleToken3() -> some View {
        return self
            .font(Font.custom("Inter-regular", size: 14))
            .textCase(.uppercase) 
    }

    func textStyleToken4() -> some View {
        return self
            .font(Font.custom("Inter-regular", size: 14))
    }

    func textStyleToken5() -> some View {
        return self
            .font(Font.custom("Abel-regular", size: 14))
            .textCase(.uppercase) 
    }

    func textStyleToken6() -> some View {
        return self
            .font(Font.custom("AR One Sans-regular", size: 14))
    }

    func textStyleToken7() -> some View {
        return self
            .font(Font.custom("Abril Fatface-regular", size: 14))
    }

    func textStyleToken8() -> some View {
        return self
            .font(Font.custom("Inter-regular", size: 14))
    }

    func textStyleToken9() -> some View {
        return self
            .font(Font.custom("Inter-regular", size: 14))
    }

    func textStyleToken10() -> some View {
        return self
            .font(Font.custom("AR One Sans-regular", size: 14))
    }

    func textStyleSnTypo() -> some View {
        return self
            .font(Font.custom("AR One Sans-regular", size: 14))
    }

    func textStyleToken11() -> some View {
        return self
            .font(Font.custom("Inter-regular", size: 14))
    }

    func textStyleToken12() -> some View {
        return self
            .font(Font.custom("Inter-regular", size: 14))
    }

    func textStyleH1() -> some View {
        return self
            .font(Font.custom("Inter-400", size: 57))
    }

    func textStyleH2() -> some View {
        return self
            .font(Font.custom("Inter-400", size: 43))
    }

    func textStyleH3() -> some View {
        return self
            .font(Font.custom("Inter-400", size: 32))
    }

    func textStyleH4() -> some View {
        return self
            .font(Font.custom("Inter-400", size: 24))
    }

    func textStyleH5() -> some View {
        return self
            .font(Font.custom("Inter-400", size: 21))
    }

    func textStyleLargeLead() -> some View {
        return self
            .font(Font.custom("Inter-400", size: 24))
    }

    func textStyleMediumLead() -> some View {
        return self
            .font(Font.custom("Inter-400", size: 21))
    }

    func textStyleButtonLabel() -> some View {
        return self
            .font(Font.custom("Inter-400", size: 21))
    }

    func textStyleParagraph() -> some View {
        return self
            .font(Font.custom("Inter-400", size: 18))
    }

    func textStyleSmallParagraph() -> some View {
        return self
            .font(Font.custom("Inter-400", size: 16))
    }

    func textStyleTinyParagraph() -> some View {
        return self
            .font(Font.custom("Inter-400", size: 12))
    }

    func textStyleTypoToken() -> some View {
        return self
            .font(Font.custom("Abhaya Libre-regular", size: 14))
    }

    func textStyleToken13() -> some View {
        return self
            .font(Font.custom("Inter-regular", size: 14))
    }

    func textStyleTypo() -> some View {
        return self
            .font(Font.custom("Inter-regular", size: 14))
    }

    func textStyleToken14() -> some View {
        return self
            .font(Font.custom("Inter-regular", size: 14))
    }

    func textStyleSnTypography() -> some View {
        return self
            .font(Font.custom("Inter-regular", size: 14))
            .underline() 
            .textCase(.lowercase) 
    }
}
