import SwiftUI

// Generated by Supernova - do not modify manually
extension View {  

    func borderToken1() -> some View {
        return self.cornerRadius(4) 
    }

    func borderWrike() -> some View {
        return self.cornerRadius(4) 
    }

    func borderNewOne() -> some View {
        return self.cornerRadius(4) 
    }

    func borderToken4() -> some View {
        return self.cornerRadius(4) 
    }
}