import SwiftUI

// Generated by Supernova - do not modify manually
public extension View {

    func shadowShadow() -> some View {
        return self.shadow(color: Color(.sRGB, red: 171/255, green: 62/255, blue: 62/255, opacity: 1), radius: 0, x: 2, y: 2) 
    }
}